name: fastapi-task-app

services: 
  backend:
    image: fastapi-task-app/backend:latest
    container_name: backend
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app:ro
      - backend-venv:/usr/src/app/venv
      - backend-logs:/usr/src/app/website/logger/logs
    env_file: 
      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432 
      - DATABASE_PASSWORD=qwerty123
      - RUN_ON_DOCKER=on
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: postgres 
    restart: unless-stopped 
    env_file: 
      - ./.env
    environment:
      - POSTGRES_DB=fastapiTest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data 
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

volumes:
  postgres-db:
  backend-venv: 
  backend-logs:

networks:
  app-network:
    driver: bridge
